### ISSUE TITLE
Syntax highlighting for CSS files

### ISSUE THREAD

**Issue by ubmit** [olivercederborg/poimandres.nvim#12]
First of all, thanks a lot for porting this theme! I love it!

I realized that the syntax highlighting for CSS files isn't close yet to what the VS Code version is.

Here is a screenshot with a simple example:

![image](https://user-images.githubusercontent.com/8797405/185610144-814b28f3-721a-46d7-918b-d09b9de1c4de.png)

**Comment by olivercederborg** [comment]
Thanks for pointing this out! And I'm glad it has value to others than me!

I'll update this asap! 🙌

**Comment by ubmit** [comment]
Sure, I love the theme. Unfortunately I don't have any experience with themes for nvim or simply vim. If I had I'd be glad to open a PR for this!

**Comment by olivercederborg** [comment]
Little update:
I am home from vacation today and will tackle this issue 👍

**Comment by ubmit** [comment]
> Little update: I am home from vacation today and will tackle this issue 👍

Thanks!!!

**Comment by olivercederborg** [comment]
From what I've tested so far the CSS syntax highlighting should now be 95% accurate compared to the OG vscode theme.
There are some limitations to treesitter which doesn't fully support @ rules with tailwind for example, but I hope this is an acceptable start :)

**Comment by ubmit** [comment]
Nice, that's awesome!
