### ISSUE TITLE
Transparent background option?

### ISSUE THREAD

**Issue by nexxeln** [olivercederborg/poimandres.nvim#14]
I use a transparent terminal, so I would love if there was a transparent background option the config.

**Comment by olivercederborg** [comment]
If you go to the configuration section of the readme, you can see how you can disable the background with `disable_background = true` 😊

**Comment by nexxeln** [comment]
> If you go to the configuration section of the readme, you can see how you can disable the background with `disable_background = true` 😊

I'm so sorry, I totally missed that.

**Comment by olivercederborg** [comment]
> > If you go to the configuration section of the readme, you can see how you can disable the background with `disable_background = true` 😊
> 
> 
> 
> I'm so sorry, I totally missed that.

Haha no worries, happy to help!
