### ISSUE TITLE
font

### ISSUE THREAD

**Issue by bryant-the-coder** [olivercederborg/poimandres.nvim#17]
what font is used in the screenshot?

**Comment by olivercederborg** [comment]
JetBrains Mono :)

**Comment by bacnx** [comment]
Hi @olivercederborg,
How you can make line height like your screenshot? :)
I tried to change line height in emulator, but it have some problem like this:
![image](https://github.com/user-attachments/assets/a7f1a923-7c31-49b5-b4c1-426b8a9c6be9)
