### ISSUE TITLE
Disabling background does not work

### ISSUE THREAD

**Issue by ervnjmsdnts** [olivercederborg/poimandres.nvim#21]
I like having a transparent background on my terminal so I tried to to disable the background using `disable_background = true` in the config setup. But it didn't work it still has it's default background.

Note: using Packer and already used :PackerSync

**Comment by olivercederborg** [comment]
What terminal are you using? 
And can you provide an example of the config used? :)

**Comment by ervnjmsdnts** [comment]
> What terminal are you using? And can you provide an example of the config used? :)

Terminal: iTerm2

Config:
```
  use {
    'olivercederborg/poimandres.nvim',
    config = function()
      require('poimandres').setup {
        bold_vert_split = false,
        dim_nc_background = false,
        disable_background = true,
        disable_float_background = true,
        disable_italics = false,
      }
    end
  }
```

**Comment by olivercederborg** [comment]
You need to set the colorscheme after the theme `setup` function has been invoked.
So if you configure the theme directly in the packer config, you could change it to:
```lua
use({
  "olivercederborg/poimandres.nvim",
  config = function()
    require("poimandres").setup({
      bold_vert_split = false,
      dim_nc_background = false,
      disable_background = true,
      disable_float_background = true,
      disable_italics = false,
    })

    vim.cmd("colorscheme poimandres")
  end
})
```

I will make this more clear in the docs 👌🏼 

Please don't hesitate to reach out again if you are still having problems 😊

**Comment by ervnjmsdnts** [comment]
Yup that fixed it. Thank you!
