### ISSUE TITLE
Disabling italics not working

### ISSUE THREAD

**Issue by caleb-freitas** [olivercederborg/poimandres.nvim#22]
Hello,

I'm pretty new to nvim world, and because of that, this may be a silly issue.

I'm using Packer, and these are my config files for poimandres

```lua
-- nvim/lua/plugins.lua
use 'olivercederborg/poimandres.nvim' 
```

Here I tried to use a part of your setup:

```lua
-- nvim/after/plugin/poimandres.rc.lua
local poimandres_present, poimandres = pcall(require, "poimandres")
if not poimandres_present then
	vim.notify("poimandres not found!")
	return
end

poimandres.setup({
	disable_italics = true,
})
```

This way, the HTML attributes are italicized. Also, the native HTML tags are white and not green. React's custom components are green, however. Thanks!

**Comment by olivercederborg** [comment]
Hey! Try and see if it could be the same issue as I described in #21 
Regarding the syntax highlighting, this is something I am aware of, and try to improve as much as I can over time.
Thank you! 🙏🏼

**Comment by caleb-freitas** [comment]
Yep. It worked. Thank you very much!

**Comment by olivercederborg** [comment]
> Yep. It worked. Thank you very much!

Awesome! Happy to help :)
