### ISSUE TITLE
Theme broken after upgrade treesitter

### ISSUE THREAD

**Issue by trangcongthanh** [olivercederborg/poimandres.nvim#25]
After accidentally upgraded my treesitter, I notices that the syntax colors are not matched with the original theme.

On left side is the neovim
On right side is the vscode
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/14819342/200157309-e2227062-a84e-4c00-acf5-34db138885de.png">

**Comment by olivercederborg** [comment]
I am working on updating the theme to support this new version of treesitter! A PR will be merged tomorrow :)
