### ISSUE TITLE
Hard to distinguish File preview and results in Telescope

### ISSUE THREAD

**Issue by OlegGulevskyy** [olivercederborg/poimandres.nvim#27]
Thank you for your efforts with this theme, I was looking for it a while back but didn't find it for neovim
Once I started using it, I noticed that Telescope support seems somewhat off, where File preview and Results are barely distinguishable.
See the image below
![image](https://user-images.githubusercontent.com/43781031/208082633-218f9723-b6d0-4cd2-bac3-cbadf827037f.png)
Is this be design or do I have an issue with it? If it's be design, do you think some sort of customizaiton can be done to allow to set some sort of different background color on those 2 fields, or something of sorts?

**Comment by hekatx** [comment]
You can override colorscheme colors by using `vim.api.nvim_set_hl` on nvim >= 0.7. For this particular case, you're looking for something like this: 
```lua
vim.api.nvim_set_hl(0, "TelescopeSelection", { bg = "#42675A" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { bg = "#42675A" })
```
Just replace `#42675A` with any color you want. If you want to override other colors, look at this plugins dir `lua/poimandres/theme.lua`, there you will find every hl group set by the colorscheme.

**Comment by Tylopilus** [comment]
Thanks you for that info
