### ISSUE TITLE
treesitter highlighting variables

### ISSUE THREAD

**Issue by TJohn0312** [olivercederborg/poimandres.nvim#30]
When using / search it highlights selected words with blue2. but it changes to a darker color for white text and teal1, to make things easier to see.
however I have vim-illuminate highlighting other uses of the word under the cursor. It highlights in blue2, and doesn't change for lighter text.
any suggestions on how to implement this, or should i just change the color to a grey

**Comment by kayuxx** [comment]
@TJohn0312 you can use the neovim api to set such an highlight using `vim.api.nvim_set_hl`.
ex:
```lua
local set_hl = vim.api.nvim_set_hl
set_hl(0, '@string', {fg = "red"})
```
or just use the vim `:hi` cmd
```vim
:hi @string guifg=red
```
