### ISSUE TITLE
Setup Transparent BG in LazyVim

### ISSUE THREAD

**Issue by adeniyii** [olivercederborg/poimandres.nvim#34]
Hey, so I'm new to nvim and went with LazyVim for an out-of -the-box experience, but I can't seem to get the transparent background going with this theme. I've seen the previous comments and tried to port the solutions to my config but no luck yet.

Here's my Poimandres config:
![Screenshot 2023-08-09 145433](https://github.com/olivercederborg/poimandres.nvim/assets/52568775/d1c44d9d-47db-403e-b15a-25ea4d4463dd)

Any idea what I'm doing wrong?

**Comment by adeniyii** [comment]
I've figured it out.

**Comment by Blankeos** [comment]
@Adeniyii share the solution? lol I'm stuck (skill issue on me)

Edit: Found it: https://github.com/olivercederborg/poimandres.nvim/issues/21#issuecomment-1265407518
